### ISSUE TITLE
Suggested layout

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/json-schema-editor#1] opened 2019-02-19 13:07 UTC
I think that during development we may wish to experiment with JSON-Editor layout properties.

We may also wish to experiment with changes to JSON Meta-Schema.
![schema editor layout](https://user-images.githubusercontent.com/1108513/53017121-2d5e7c00-3447-11e9-91bc-7126a7b261cc.png)

Once the form (& meta-schema) have stabilised we may wish to remove some elements.

**Comment by pmk65** [comment] 2019-02-19 14:11
I suggest you do the preview in an iframe, similar to what I did here: https://github.com/pmk65/jedemov2
As injecting script and CSS directly on the page (like the docs/demo.html in JSON-Editor does) leads to problems as you can't unload them again.

Also use the ACE Editor for schema editing/display. It's really simple to setup and is much nicer than a standard textarea field. 😄

**Comment by Franciman** [comment] 2019-02-20 12:22
>  suggest you do the preview in an iframe, similar to what I did here: https://github.com/pmk65/jedemov2
As injecting script and CSS directly on the page (like the docs/demo.html in JSON-Editor does) leads to problems as you can't unload them again.

I use a plain div and just load the JSONEditor schema from the other JSONEditor value, it seems to be working fine, also when reloading.

Thanks for the ACE Editor, it's really cool!

**Comment by pmk65** [comment] 2019-02-20 14:10
If you want the preview to be configurable (Changing CSS framework, Iconlib and adding 3rd-party scripts), then you will get into problems if you just use a div on the main page. As you can't isolate the CSS from the framework or unload unused scripts later.
Using an iframe isolates the JSON-Editor form from CSS and Scripts on the main page.

The [docs/demo.html](https://rawgit.com/json-editor/json-editor/master/docs/demo.html) uses the "div on page" method.
If you switch CSS framework, the ENTIRE page layout changes, not just the JSON-Editor form. 
So with this method you will have to make your design compatible with ALL the supported frameworks. (And HTML and Barebones will make everything look bad 😁 )

That's why I opted for using an iframe in my playground editor. So I can change frameworks etc. without affecting the general layout. I then update the iframe like this:
````javascript
    // Iframe
    var jeIframeEl = document.querySelector('iframe');
    var jeIframe = jeIframeEl.contentWindow || ( jeIframeEl.contentDocument.document || jeIframeEl.contentDocument);
    var bData = new Blob([createIframeContent(code)], {type: 'text/html'});
    jeIframeEl.onload = function() { window.URL.revokeObjectURL(bData); };
    jeIframeEl.src = window.URL.createObjectURL(bData);
````

**Comment by Franciman** [comment] 2019-02-20 20:38
I see, thanks for the suggestion

**Comment by pmk65** [comment] 2019-02-20 20:58
Another hint. When you use the ACE Editor, `setValue()` function, then do this just after:

````javascript
metaSchema.session.getSelection().clearSelection();
metaSchema.resize();
````
The 1st line will remove the selection of the content (I found it annoying that ACE Editor selects the value you insert)
The 2nd ensures that the Ace Editor visible content is updated. (If the ACE Editor is hidden when you set a value, the display doesn't update when you make it visible: But first when you put focus to it.)

**Comment by Franciman** [comment] 2019-02-27 10:37
@pmk65 thank you.
Regarding `iframe` we have decided to stick to `bootstrap4` theme only (with `fontawesome5` icons), so can we keep using the `div` or do you still suggest using an `iframe` ?

**Comment by pmk65** [comment] 2019-02-27 11:17
The problem is the external libraries. Some, like Select2 and Selectize perform similar actions (Modify select boxes) and doesn't work well together. And some external libs can't be destroyed (revert the form elements to original state)
To illustrate the problem, go to the [demo.html](https://rawgit.com/json-editor/json-editor/master/docs/demo.html) and then click the items in "Include External Libraries" 1-by-1. Then scroll down the page and you'll see some "garbage" from one or more of the external libs. This is because they are not destroyed.

BTW: If you choose to use iframe, do **NOT** use the `URL.createObjectURL()` method I described earlier.
As I discovered that it prevents scripts from getting path info from window.location (which is required for resolving $refs). Instead you'll have to use `document.write()` See my tests here: https://codepen.io/pmk/pen/wOwoyW

**Comment by pmk65** [comment] 2019-02-27 15:32
The problem is already present in your latest release. Try clicking the options "Disable Properties button", and you'll notice it disables the buttons on **both** the result form and your editor form. 
(It is possible to set the options for a single instance of the editor, but then you'll have to set the options in the schema and not globally)

**Comment by Franciman** [comment] 2019-02-27 15:39
Oh, that was intended, but I see your point. Thank you very much for the help.
Ok we need to discuss what we want, because I think we're going to follow the path of not making the editor style and external libraries modifiable by the user

**Comment by pmk65** [comment] 2019-02-27 16:04
Change `jseditor` to the instance of the previewEditor, and the form will have a "Save Schema" button. 

````javascript
jseditor.on('ready', function() {
  var button = jseditor.root.getButton('Save Schema As File', 'save', 'Save Schema As File'),
  button_holder = jseditor.root.theme.getHeaderButtonHolder();
  button_holder.appendChild(button);
  jseditor.root.header.parentNode.insertBefore(button_holder, jseditor.root.header.nextSibling);

  button.addEventListener('click', function(e) {
    e.preventDefault();
    var example = jseditor.schema,
    filename = 'schema.json',
    blob = new Blob([JSON.stringify(example, null, 2)], {
      type: "application/json;charset=utf-8"
    });

    if (window.navigator && window.navigator.msSaveOrOpenBlob) {
      window.navigator.msSaveOrOpenBlob(blob, filename);
    } else {
      var a = document.createElement('a');
      a.download = filename;
      a.href = URL.createObjectURL(blob);
      a.dataset.downloadurl = ['text/plain', a.download, a.href].join(':');

      a.dispatchEvent(new MouseEvent('click', {
        'view': window,
        'bubbles': true,
        'cancelable': false
      }));
    }
  }, false);
});
````

**Comment by IanMayo** [comment] 2019-03-08 10:34
@Franciman - is this issue completed?

**Comment by Franciman** [comment] 2019-03-08 12:03
I think there is only two things to be discussed:
- Are we happy with `div` rendering or do we need the extra power of `iframe` ?
- Do we need the `Save Schema` button?

Regarding the `div` vs `iframe` In the final product I think the `div` is fine, since the options and extra libs are all fixed, so no need to change them at runtime and therefore I'd prefer to keep the code simpler.

In the development version it seems like the current behavior is acceptable:
>The problem is already present in your latest release. Try clicking the options "Disable Properties button", and you'll notice it disables the buttons on both the result form and your editor form.

This doesn't seem to be a problem, or is it?

**Comment by IanMayo** [comment] 2019-03-08 12:21
* `div` rendering. If `div` works, then that's fine
* `save schema`.  No, we don't need to save them.

You're right. I _don't think_ we will have different display format properties across the editor & preview components.

**Comment by pmk65** [comment] 2019-03-09 16:36
>
>     * `save schema`.  No, we don't need to save them.
> 

Then how are you going to use the resulting schema you create?
With the JSON Button hidden/disabled there's no way of viewing or saving the final schema source, which renders the editor pretty useless.

**Comment by IanMayo** [comment] 2019-03-09 18:05
Thanks for that @pmk65 .  I'm targeting a specific usage of the editor, where the outer container code will provide/retrieve the finished document.

But, that's being too blinkered. You're right.  We should keep the `Save` functionality.

**Closed as completed** 2019-03-13 09:17 UTC
